DROP DATABASE IF EXISTS burgers;
CREATE DATABASE burgers;
USE burgers;

CREATE TABLE burgers (
	id Int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	burger_name VARCHAR( 255 ) NOT NULL,
	devoured BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL
);
 
